# Generated by Django 4.2.5 on 2023-09-21 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('book', '0002_alter_book_borrowing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.buser'),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('Available', 'Available'), ('Taken', 'Taken')], default='Available', max_length=10),
        ),
    ]
